device/urls.py
from django.conf.urls import patterns, url

from device import views
urlpatterns = patterns('',
	url(r'^$',views.index,name="index"),
	url(r'^changepassword/',views.changepassword,name="changepassword"),
	url(r'^search/(?P<word>\w+)',views.search,name="search"),

	url(r'^user/',views.user,name="user"),
	url(r'^adduser/',views.adduser,name="adduser"),
	url(r'^edituser/(?P<id>\d+)',views.edituser,name="edituser"),
	url(r'^resetpass/(?P<id>\d+)',views.resetpass,name="resetpass"),
	url(r'^removeuser/(?P<id>\d+)',views.removeuser,name="removeuser"),

	url(r'^maintain/(?P<id>\d+)?',views.maintain,name="maintain"),
	url(r'^scrap/(?P<id>\d+)?',views.scrap,name="scrap"),
	url(r'^delete/(?P<target>\w+)/(?P<id>\d+)',views.delete,name="delete"),
	url(r'^maintainback/(?P<id>\d+)',views.maintainback,name="maintainback"),
	url(r'^add/(?P<action>\w+)',views.add,name="add"),
	url(r'^get/(?P<target>\w+)/(?P<id>\d+)',views.get,name="get"),
)

jxnu/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from jxnu.views import jxnu_login,jxnu_logout
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jxnu.views.home', name='home'),
    # url(r'^jxnu/', include('jxnu.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$','device.views.index'),
    url(r'^login/',jxnu_login,name="login"),
    url(r'^logout/',jxnu_logout,name="logout"),

    url(r'^admin/', include(admin.site.urls)),
    url(r'device/',include('device.urls',namespace="device")),
)

jxnu/forms.py
#encoding:utf-8
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='用户名',max_length=50)
	password = forms.CharField(label= '密码',max_length=32, widget=forms.PasswordInput)

jxnu/views.py
#encoding:utf-8
from django.http import HttpResponse
from django.template import Context,loader,RequestContext
from  django.shortcuts import render_to_response,redirect

from django.contrib.auth import authenticate,login,logout

from jxnu.forms import  LoginForm

def jxnu_login(request):
	if request.user.is_authenticated():
		return redirect('/')
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username,password=password)
		if user:
			login(request,user)
			return redirect('/')
		else:
			return HttpResponse("无效的用户名和密码")
	else:
		loginform = LoginForm()
		return render_to_response('login.html',{'loginform':loginform},context_instance=RequestContext(request))

def jxnu_logout(request):
	if request.user.is_authenticated():
		logout(request)
		return redirect('/')

jxnu/templates/header.html
<div class="container" style="margin-top:40px;">
  <div class="row">
        <div class="span12">
          <img src="/static/img/top.jpg">
        </div>
      </div>
</div>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="row">
         <a class="brand span2" href="/">系统首页</a>
      <div class="nav-collapse collapse">
        <ul class="nav span10" id="header_nav">
          {% if perms.device.maintain_device %}
          <li {% if section == "add"%}class="active" {% endif %} class="dropdown">
           <a role="button" class="dropdown-toggle" data-toggle="dropdown">添加设备<b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "device:add" "device" %}">添加设备</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "device:add" "devtype" %}">添加型号</a></li>
               <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "device:add" "devcata" %}">添加分类</a></li>
            </ul>
          </li>
          <li {% if section == "maintain"%}class="active" {% endif %}><a href="{% url 'device:maintain'%}">维修设备</a></li>
          {% endif %}
          {% if perms.auth.add_user %}
          <li class="dropdown{% if section == "user"%} active{% endif %}">
             <a role="button" class="dropdown-toggle" data-toggle="dropdown">用户管理<b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'device:user'%}">用户列表</a></li>
              <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url "device:adduser" %}">添加用户</a></li>
            </ul>
          </li>
          {% endif %}
          <li style="float:right"><a href="{% url 'logout'%}">退出系统</a></li>
          <li {% if section == "changepassword"%}class="active" {% endif %} style="float:right"><a href="{% url 'device:changepassword'  %}">修改密码</a></li>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>

jxnu/templates/layout.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="/static/index.css">
  <script src="/static/js/seajs/sea.js" data-main="jxnu/main" id="seajsnode"></script>
  <title>江西师范大学教学设备管理系统</title>
</head>
<body>
  {% include 'header.html'%}
  <div class="container page">
      {% if message.exist %}
      <div class="alert alert-{{ message.type }}">
        {{ message.content }}
      </div>
      {% endif %}
    {% block body %}{% endblock %}
  </div>
</body>
</html>

jxnu/templates/login.html
<!DOCTYPE HTML>
<html>
<head>
	<title>
		江西师范大学教学设备管理系统
	</title>
	<link rel="stylesheet" type="text/css" href="/static/login.css">
</head>
<body>
<form action="{% url 'login' %}" method="POST">{% csrf_token %}
	<div class="login-view">
		{{ loginform.as_p }}
		<p>
			<button type="submit">登录</button>
		</p>
	</div>
	
</form>
</body>
</html>